hiányzó paraméterek javítása
src/App.tsx(13,8): error TS2739: Type '{}' is missing the following properties from type 'NavbarProps': previewConfig, generatedCode, gameId, setGameId